#!/bin/bash

PAYARA_MICRO=target/payara-micro.current.jar

HZ_CLUSTER_NAME="colabLocal_$(hostname)"

HEAP=256M

THE_WAR=./target/colab-webapp-0.1/

DEBUG_PORT=9009
DEBUG="false"
DEBUG_OPTS=

JAVA_HOME=""
JAVA_EXECUTABLE=""

function show_help {
    echo "Usage: ./run [OPTIONS]"
    echo " -g             debug mode"
    echo " -j JAVA_PATH   java path (default is ${JAVA_HOME})"
    echo " -m HEAP        heap size (default is ${HEAP})"
    echo " -p PORT        debug port (default is ${DEBUG_PORT})"
    echo " -w WAR_PATH    war path (default is ${THE_WAR})"
}

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

while getopts "h?gm:p:w:j:" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    g)  DEBUG="true"
        ;;
    j)  JAVA_HOME=$OPTARG
        ;;
    m)  HEAP=$OPTARG
        ;;
    p)  DEBUG_PORT=$OPTARG
        ;;
    w)  THE_WAR=$OPTARG
        ;;
    esac
done


if [ ${DEBUG} == "true" ]; then
    DEBUG_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=${DEBUG_PORT},server=y,suspend=n"
    echo DEBUG_OPTS ${DEBUG_OPTS}
    echo DEBUG_PORT ${DEBUG_PORT}
fi

echo HEAP ${HEAP}
echo WAR ${THE_WAR}

trap 'echo "TERM";kill -TERM $PID;' TERM INT

# to enable http2 support
HTTP2_OPTS=-Xbootclasspath/a:grizzly-npn-bootstrap.jar

#if java home is empty, use java, if not, use JAVA_HOME/java
if [ "${JAVA_HOME}xxx" = "xxx" ]; then JAVA_EXECUTABLE=java; else JAVA_EXECUTABLE="${JAVA_HOME}/java"; fi


# if java has the list-modules options, it's java 9+
${JAVA_EXECUTABLE} --list-modules > /dev/null 2> /dev/null

if [ $? -eq 0 ]; then
    echo JAVA 9+ detected: enable extra options
    JDK_EXTRA_OPTS="--add-modules java.se
        --add-opens=java.base/jdk.internal.loader=ALL-UNNAMED 
        --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED 
        --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED 
        --add-opens=java.base/java.lang=ALL-UNNAMED
        --add-opens=java.base/java.net=ALL-UNNAMED
        --add-opens=java.base/java.nio=ALL-UNNAMED
        --add-opens=java.base/java.util=ALL-UNNAMED
        --add-opens=java.base/sun.nio.ch=ALL-UNNAMED 
        --add-opens=java.base/sun.net.www.protocol.jar=ALL-UNNAMED
        --add-opens=java.naming/javax.naming.spi=ALL-UNNAMED
        --add-opens=java.logging/java.util.logging=ALL-UNNAMED
        --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
        --add-opens=java.management/sun.management=ALL-UNNAMED 
        --add-opens=java.base/sun.net.www.protocol.jrt=ALL-UNNAMED"
    GC="-XX:+UnlockExperimentalVMOptions -XX:+UseZGC"
    GC="-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1MaxNewSizePercent=75 -XX:G1NewSizePercent=40 -XX:MaxGCPauseMillis=2500"
# -XX:ConcGCThreads=<number> – Basic logging: -Xlog:gc – Detailed logging useful when tuning: -Xlog:gc* 
else
    echo JAVA 8 detected
    JDK_EXTRA_OPTS=""
    GC="-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1MaxNewSizePercent=75 -XX:G1NewSizePercent=40 -XX:MaxGCPauseMillis=2500"
fi


${JAVA_EXECUTABLE} ${DEBUG_OPTS} ${JDK_EXTRA_OPTS} ${SSL_OPTS} ${GC} ${HTTP2_OPTS} \
    -XX:+UseStringDeduplication -XX:+UnlockDiagnosticVMOptions \
    -Dproduct.name= -XX:+ParallelRefProcEnabled -XX:+UseCompressedOops -XX:-UseLoopPredicate \
    -Xms${HEAP} -Xmx${HEAP} \
    -Djava.security.egd=file:/dev/urandom \
    -Dcolab.database=colab_prod \
    -Declipselink.cache.coordination.protocol=fish.payara.persistence.eclipselink.cache.coordination.HazelcastPublishingTransportManager \
    -Declipselink.cache.coordination.channel=${HZ_CLUSTER_NAME} \
    -jar ${PAYARA_MICRO} --deploy ${THE_WAR} --clusterName ${HZ_CLUSTER_NAME} \
    --contextroot "" \
    --interfaces 127.0.0.1 \
    --systemproperties colab.properties
    --autobindhttp --autobindssl &
PID=$!

wait $PID
trap - TERM INT
wait $PID
EXIT_STATUS=$?

echo "Terminated"
