/*
 * The coLAB project
 * Copyright (C) 2021 AlbaSim, MEI, HEIG-VD, HES-SO
 *
 * Licensed under the MIT License
 */

import { Change } from 'colab-rest-client';
import * as React from 'react';
import { ChangeTreeRaw } from '../live/ChangeTree';

export default function Debugger(): JSX.Element {
  const revision = 'ws-s1::17';

  const changes: Change[] = [
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::17',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 8, t: 'I', v: 'd' }],
      revision: 'ws-s1::18',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::18',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 9, t: 'I', v: "'ac" }],
      revision: 'ws-s1::19',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::19',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 12, t: 'I', v: 'cord ' }],
      revision: 'ws-s1::20',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::20',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 17, t: 'I', v: 'aklo' }],
      revision: 'ws-s1::21',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::21',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ l: 2, o: 19, t: 'D' }],
      revision: 'ws-s1::22',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::22',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ l: 1, o: 18, t: 'D' }],
      revision: 'ws-s1::23',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::23',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 27, t: 'I', v: 'c' }],
      revision: 'ws-s2::34',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::34',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 18, t: 'I', v: 'l' }],
      revision: 'ws-s1::24',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::24',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 29, t: 'I', v: "'est" }],
      revision: 'ws-s2::35',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::24',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 19, t: 'I', v: 'ors ' }],
      revision: 'ws-s1::25',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::25',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 23, t: 'I', v: 'j' }],
      revision: 'ws-s1::26',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::26',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 38, t: 'I', v: ' ' }],
      revision: 'ws-s2::36',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::36',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 24, t: 'I', v: 'e ' }],
      revision: 'ws-s1::27',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::27',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 26, t: 'I', v: 'pren' }],
      revision: 'ws-s1::28',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::28',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 30, t: 'I', v: 'ds la ' }],
      revision: 'ws-s1::29',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::29',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 51, t: 'I', v: 'gen' }],
      revision: 'ws-s2::37',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::37',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 54, t: 'I', v: 'til' }],
      revision: 'ws-s2::38',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::38',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 36, t: 'I', v: 'lugn' }],
      revision: 'ws-s1::30',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::30',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 61, t: 'I', v: '.' }],
      revision: 'ws-s2::39',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::39',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 40, t: 'I', v: 'e ' }],
      revision: 'ws-s1::31',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::31',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 64, t: 'I', v: ' ' }],
      revision: 'ws-s2::40',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::40',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 65, t: 'I', v: "j'a" }],
      revision: 'ws-s2::41',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::41',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ l: 2, o: 40, t: 'D' }],
      revision: 'ws-s1::32',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::32',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 66, t: 'I', v: 'i' }],
      revision: 'ws-s2::42',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::42',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ l: 1, o: 39, t: 'D' }],
      revision: 'ws-s1::33',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::33',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 66, t: 'I', v: 'me' }],
      revision: 'ws-s2::43',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::43',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ l: 2, o: 37, t: 'D' }],
      revision: 'ws-s1::34',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::34',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 66, t: 'I', v: ' ' }],
      revision: 'ws-s2::44',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::44',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 37, t: 'I', v: 'ui' }],
      revision: 'ws-s1::35',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::35',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 69, t: 'I', v: 'b' }],
      revision: 'ws-s2::45',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::45',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 70, t: 'I', v: 'ien ' }],
      revision: 'ws-s2::46',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::46',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ l: 1, o: 38, t: 'D' }],
      revision: 'ws-s1::36',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::36',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [
        { l: 1, o: 37, t: 'D' },
        { o: 38, t: 'I', v: 'ig' },
      ],
      revision: 'ws-s1::37',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::36',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 73, t: 'I', v: 'auss' }],
      revision: 'ws-s2::47',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::47',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 39, t: 'I', v: 'ne' }],
      revision: 'ws-s1::38',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::38',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 80, t: 'I', v: 'i ' }],
      revision: 'ws-s2::48',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::48',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 41, t: 'I', v: ' ' }],
      revision: 'ws-s1::39',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::39',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 83, t: 'I', v: 'é' }],
      revision: 'ws-s2::49',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::49',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 42, t: 'I', v: 'num' }],
      revision: 'ws-s1::40',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::40',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 87, t: 'I', v: 'c' }],
      revision: 'ws-s2::50',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::50',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 45, t: 'I', v: 'é' }],
      revision: 'ws-s1::41',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::41',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 89, t: 'I', v: 'rir' }],
      revision: 'ws-s2::51',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::51',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 46, t: 'I', v: 'ro ' }],
      revision: 'ws-s1::42',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::42',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 95, t: 'I', v: 'e ' }],
      revision: 'ws-s2::52',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::52',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 49, t: 'I', v: 'u' }],
      revision: 'ws-s1::43',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::43',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 98, t: 'I', v: 'en ' }],
      revision: 'ws-s2::53',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::53',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 50, t: 'I', v: 'n c' }],
      revision: 'ws-s1::44',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::44',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 53, t: 'I', v: 'ar ' }],
      revision: 'ws-s1::45',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::44',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 104, t: 'I', v: 'des' }],
      revision: 'ws-s2::54',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::54',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 110, t: 'I', v: 'sous' }],
      revision: 'ws-s2::55',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::55',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 114, t: 'I', v: '. ' }],
      revision: 'ws-s2::56',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::56',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 116, t: 'I', v: 'C' }],
      revision: 'ws-s2::57',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::57',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 61, t: 'I', v: ' ' }],
      revision: 'ws-s1::47',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::55',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 56, t: 'I', v: 'mince' }],
      revision: 'ws-s1::46',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::47',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 118, t: 'I', v: 'o' }],
      revision: 'ws-s2::58',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::58',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 62, t: 'I', v: 'tu' }],
      revision: 'ws-s1::48',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::48',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 126, t: 'I', v: 'mme ' }],
      revision: 'ws-s2::59',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::59',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 64, t: 'I', v: ' me ' }],
      revision: 'ws-s1::49',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::49',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 68, t: 'I', v: 'ra' }],
      revision: 'ws-s1::50',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::50',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 70, t: 'I', v: 'ttrap' }],
      revision: 'ws-s1::51',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::51',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 75, t: 'I', v: 'e' }],
      revision: 'ws-s1::52',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::52',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 76, t: 'I', v: ' ' }],
      revision: 'ws-s1::53',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::53',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 77, t: 'I', v: 'je ' }],
      revision: 'ws-s1::54',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::53',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 143, t: 'I', v: 'R' }],
      revision: 'ws-s2::60',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::60',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 80, t: 'I', v: 'ne ' }],
      revision: 'ws-s1::55',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::55',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 83, t: 'I', v: 'suis ' }],
      revision: 'ws-s1::56',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::56',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 88, t: 'I', v: 'pas d' }],
      revision: 'ws-s1::57',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::57',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 93, t: 'I', v: "'ac" }],
      revision: 'ws-s1::58',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::58',
      id: 3,
      liveSession: 'ws-s1',
      microchanges: [{ o: 96, t: 'I', v: 'cord' }],
      revision: 'ws-s1::59',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s1::58',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ l: 1, o: 162, t: 'D' }],
      revision: 'ws-s2::61',
    },
    {
      '@class': 'Change',
      atClass: 'TextDataBlock',
      atId: 3,
      basedOn: 'ws-s2::61',
      id: 3,
      liveSession: 'ws-s2',
      microchanges: [{ o: 166, t: 'I', v: 'je ' }],
      revision: 'ws-s2::62',
    },
  ];
  return (
    <div>
      <ChangeTreeRaw changes={changes} revision={revision} verbosity="FULL" />
    </div>
  );
}
