name: Build gh-pages

on:
  push:
    branches: [ test-ci ]

jobs:
  site:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: colab_test
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: colab_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.5'
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install no tests
      run: mvn -Dreporting -B -DskipTests install
    - name: Build Site
      run: mvn -Dreporting -B site site:stage