name: Build gh-pages

on:
  push:
    branches: [main]

jobs:
  build-site:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: colab_test
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: colab_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.1
          cache: yarn
          cache-dependency-path: |
            colab-webapp/yarn.lock
            colab-tests/src/test/node/yarn.lock

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
          cache: 'maven'

      - name: Maven package without tests
        run: mvn -Dreporting -B -DskipTests install

      - name: Maven build Site
        run: mvn -Dreporting -B site site:stage

      - name: Push GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/staging
